CC = gcc
CFLAGS = -Wall -O2

EXEC = greedy backtracking dp

.PHONY: all run clean

all: $(EXEC) run

greedy: Greedy.c
	$(CC) $(CFLAGS) Greedy.c -o greedy

backtracking: Backtracking.c
	$(CC) $(CFLAGS) Backtracking.c -o backtracking

dp: PD.c
	$(CC) $(CFLAGS) PD.c -o dp

run: $(EXEC)
	@mkdir -p output
	@# Iteram prin fiecare fisier .txt din folderul tests
	@for test in tests/*.txt; do \
		nume=$$(basename $$test .txt); \
		\
		./greedy $$test output/temp_greedy.txt; \
		./dp $$test output/temp_dp.txt; \
		./backtracking $$test output/temp_back.txt; \
		\
		echo "Rezultate Greedy:" > output/output_$$nume.txt; \
		cat output/temp_greedy.txt >> output/output_$$nume.txt; \
		\
		echo "" >> output/output_$$nume.txt; \
		echo "Rezultate DP:" >> output/output_$$nume.txt; \
		cat output/temp_dp.txt >> output/output_$$nume.txt; \
		\
		echo "" >> output/output_$$nume.txt; \
		echo "Rezultate Backtracking:" >> output/output_$$nume.txt; \
		cat output/temp_back.txt >> output/output_$$nume.txt; \
		\
		rm output/temp_greedy.txt output/temp_dp.txt output/temp_back.txt; \
	done

clean:
	rm -f greedy backtracking dp
	rm -rf output